apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-petclinic-datasource
  labels:
     grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.svc.cluster.local
      access: proxy
      isDefault: true
